To `polkadot-v0.9.38`
darwinia-network/darwinia pull request #1007
Opened 2023-03-10 07:13 UTC by jiguantong

- [x] frontier
- [x] moonbeam
- [x] cumulus
- [x] darwinia-messages-substrate
- [x] remove substrate&cumulus patch
- [x] fix compilation
- [x] replace prepare branch
- [ ] merge after darwinia2.0 is online

2023-03-27 18:35 UTC, AurevoirXavier requested changes
We should keep the assertion patch.

2023-03-28 02:38 UTC, jiguantong commented
Cumulus patch branch: https://github.com/paritytech/cumulus/compare/polkadot-v0.9.38...darwinia-network:cumulus:remove-assertion-v0.9.38

2023-03-28 05:42 UTC, AurevoirXavier commented on Cargo.toml
> +parachain-info                        = { git = "https://github.com/darwinia-network/cumulus", branch = "remove-assertion-v0.9.38" }
Why don't we need the `default-features = false` here?

2023-03-28 05:43 UTC, AurevoirXavier commented on Cargo.toml
> +sp-timestamp                               = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
Why don't we need the `default-features = false` here?

2023-03-28 05:43 UTC, AurevoirXavier commented on Cargo.toml
> +frame-benchmarking                         = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38" }
I think we could remove all the `default-features` in the patch section.

2023-03-28 05:44 UTC, AurevoirXavier commented on Cargo.toml
> +fp-storage                     = { git = "https://github.com/darwinia-network/frontier", branch = "polkadot-v0.9.38" }
default features? @boundless-forest

2023-03-28 05:45 UTC, AurevoirXavier commented on Cargo.toml
> +cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/cumulus.git", branch = "polkadot-v0.9.38" }
default features?

2023-03-28 05:48 UTC, merged