Add spender tracks
darwinia-network/darwinia pull request #1419
Opened 2024-03-01 01:48 UTC by AurevoirXavier

2024-03-04 06:25 UTC, hackfisher requested changes
Where are the configuration for maximum of tokens this track can spend?

2024-03-04 06:57 UTC, hackfisher commented
> Where are the configuration for maximum of tokens this track can spend?

https://github.com/polkadot-fellows/runtimes/blob/f1fb358193fb9e261ee08dc60a9b606b30479865/relay/polkadot/src/governance/origins.rs#L144-L152

2024-03-05 08:11 UTC, hackfisher approved these changes

2024-03-05 08:52 UTC, merged

2024-03-07 01:21 UTC, boundless-forest commented on runtime/crab/src/pallets/governance/origin.rs
>  	decl_unit_ensures!(ReferendumCanceller, ReferendumKiller, WhitelistedCaller, GeneralAdmin);
Why the `decl_unit_ensures` in Crab doesn't contain the `MediumSpender` and `BigSpender`?