Darwinia Mainnet(Dev)
darwinia-network/darwinia pull request #535
Opened 2020-09-15 09:15 UTC by AurevoirXavier

2020-09-16 11:17 UTC, wuminzhe commented on node/service/src/chain_spec.rs
> +	properties.insert("ss58Format".into(), 42.into());
42 for mainnetdev?

2020-09-16 11:23 UTC, HackFisher commented on node/service/src/chain_spec.rs
> +	properties.insert("ss58Format".into(), 42.into());
> 42 for mainnetdev?

good catch

2020-09-16 11:40 UTC, wuminzhe commented on node/service/src/chain_spec.rs
> +			payout_fraction: Perbill::from_percent(50),
50% or 40%?

2020-09-16 11:42 UTC, wuminzhe commented on node/service/src/chain_spec.rs
> +		darwinia_vesting: Some(Default::default()),
add vestings when not dev?

2020-09-16 11:56 UTC, wuminzhe commented on node/service/src/chain_spec.rs
> +			..Default::default()
token address?

2020-09-16 11:59 UTC, wuminzhe commented on node/service/src/chain_spec.rs
> +			ring_locked: 1_179_562_684_772_882_521,
This value is not calculated based on mapped rings?

2020-09-16 12:20 UTC, wuminzhe commented on runtime/darwinia/src/lib.rs
> +	pub const TransactionByteFee: Balance = 500 * MICRO;
0.0005 RING

2020-09-16 15:34 UTC, AurevoirXavier commented
@HackFisher Please provide 2 vesting account.

2020-09-16 16:38 UTC, HackFisher commented
> @HackFisher Please provide 2 vesting accounts.

Sent to you through PM

2020-09-16 16:38 UTC, HackFisher commented
> @HackFisher Please provide 2 vesting accounts.

Sent to you through PM

2020-09-17 02:20 UTC, HackFisher requested changes
Better to bump crab runtime version too, cause there are changes in common.

2020-09-17 06:18 UTC, HackFisher approved these changes

2020-09-17 06:18 UTC, merged