Tag v0.11.0
darwinia-network/darwinia pull request #666
Opened 2021-06-11 10:27 UTC by AurevoirXavier

2021-06-16 02:23 UTC, HackFisher commented
Need to check HeaderMMR pallet storage name, if dependency is using new  frame v2 

https://github.com/darwinia-network/darwinia/blob/711c8c5c38b9288ab3aa99a297a36bbb5b190294/runtime/crab/src/lib.rs#L192 

Might be `"HeaderMMR" --> "DarwiniaHeaderMMR"`

2021-06-28 08:46 UTC, HackFisher requested changes
Due to the changes in https://github.com/darwinia-network/darwinia-common/pull/673 and

https://github.com/darwinia-network/darwinia-common/compare/darwinia-v0.10.0..xavier-darwinia-v0.10.1

This darwinia-common companion and maybe also migration need to be upgraded.

Need carefully review considering the changes in darwinia-v0.10.1

2021-07-01 09:26 UTC, HackFisher requested changes
Current base branch `master` is using the deprecate commit https://github.com/darwinia-network/darwinia-common/commit/4e2a5dff2b30cb37a404466f00953767a75b1980 before mmr patch.

After the runtimes in v0.10.1 be applied, the dependency will require to be changed to commit after mmr patch(using new header mmr pallet).

https://github.com/darwinia-network/substrate-update-tracking/issues/19

If we use commits after darwinia-v0.11.1, check the migration differences between these substrate version(companion polkadot can be used as reference).

2021-07-19 09:57 UTC, HackFisher commented
Related polkadot release with same substrate dependency:

https://github.com/paritytech/polkadot/releases/tag/v0.9.0

What's the changes cause the mandatary upgrade for the nodes?

The new host function mentioned in polkaodt v0.9.0? Any related pull request links to this break changes?

2021-07-20 06:45 UTC, AsceticBear commented on CHANGELOG.md
> +  - #675
https://github.com/darwinia-network/darwinia-common/pull/675?

2021-07-20 06:46 UTC, AurevoirXavier commented on CHANGELOG.md
> +  - #675
Self repo link.

2021-07-20 06:46 UTC, AurevoirXavier commented on CHANGELOG.md
> +  - #675
#675

2021-07-20 07:19 UTC, AsceticBear commented
> The new host function mentioned in polkadot v0.9.0? Any related pull request links to this break changes?

The test result show like this: https://github.com/darwinia-network/darwinia/pull/662#issuecomment-857621646

2021-07-20 07:22 UTC, HackFisher commented
> > The new host function mentioned in polkadot v0.9.0? Any related pull request links to this break changes?
> 
> The test result show like this: [#662 (comment)](https://github.com/darwinia-network/darwinia/pull/662#issuecomment-857621646)

https://github.com/paritytech/substrate/pull/8655

2021-07-20 07:23 UTC, AurevoirXavier commented
> > > The new host function mentioned in polkadot v0.9.0? Any related pull request links to this break changes?
> > 
> > 
> > The test result show like this: [#662 (comment)](https://github.com/darwinia-network/darwinia/pull/662#issuecomment-857621646)
> 
> [paritytech/substrate#8655](https://github.com/paritytech/substrate/pull/8655)

Already linked in CHANGELOG

2021-07-20 07:40 UTC, AurevoirXavier commented on CHANGELOG.md
> +  - Crab UTC 2021-07-21 ~ 07-24-2021
@HackFisher

2021-07-20 07:40 UTC, AurevoirXavier commented on CHANGELOG.md
> +  - Darwinia UTC 07-28-2021 ~ 08-01-2021
@HackFisher

2021-07-20 07:44 UTC, HackFisher commented on CHANGELOG.md
> +  - Darwinia UTC 07-28-2021 ~ 08-01-2021
v0.11.0 darwinia在 mmr 裁剪期间的预期内存是多少?

2021-07-20 07:46 UTC, HackFisher commented on CHANGELOG.md
> +**请尽快升级您的节点！！否则升级后，您的节点将有可能不会同步新的区块。**
```suggestion
**请尽快升级您的节点！！否则在Runtime升级后，您的节点将有可能不会同步新的区块。**
```

2021-07-20 07:48 UTC, AurevoirXavier commented on CHANGELOG.md
> +  - Darwinia UTC 07-28-2021 ~ 08-01-2021
<img width="38" alt="image" src="https://user-images.githubusercontent.com/16152305/126282213-8ba03d1f-1888-4e6f-bc0a-bdded8f3b6a8.png">

Avg: 0.8g ~ 1.2g

Recommend to reserve: 1.5g ~ 2.5g

2021-07-20 07:48 UTC, AsceticBear commented on CHANGELOG.md
> +**请尽快升级您的节点！！否则升级后，您的节点将有可能不会同步新的区块。**
~在Runtime升级~ ->  在 Runtime 升级

2021-07-20 07:51 UTC, AurevoirXavier commented on CHANGELOG.md
> +**请尽快升级您的节点！！否则升级后，您的节点将有可能不会同步新的区块。**
> ~在Runtime升级~ -> 在 Runtime 升级

Updated.

2021-07-20 08:02 UTC, HackFisher commented on CHANGELOG.md
> +  - Crab UTC 07-21-2021 ~ 07-24-2021
```suggestion
  - Crab Now ~ UTC 07-24-2021
```

2021-07-20 08:03 UTC, HackFisher commented on CHANGELOG.md
> +  - Darwinia UTC 07-28-2021 ~ 08-01-2021
```suggestion
  - Darwinia Now ~ UTC 07-28-2021
```

2021-07-20 08:14 UTC, HackFisher approved these changes

2021-07-20 08:15 UTC, merged